apiVersion: v1
kind: Namespace
metadata:
  name: wp-namespace
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-configmap
  namespace: wp-namespace
data:
  WORDPRESS_DB_HOST: "db-service.db-namespace.svc.cluster.local"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_NAME: "wordpress"

---

apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wp-namespace
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  namespace: wp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-app
        image: wordpress:latest
        envFrom:
        - configMapRef:
            name: wp-configmap
        - secretRef:
            name: wp-secret        
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: wp-service
  namespace: wp-namespace
spec: 
  selector:
    app: wordpress
  ports:
      - port: 80
        targetPort: 80
  type: ClusterIP