apiVersion: v1
kind: Namespace
metadata:
  name: db-namespace
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: db-namespace
data:
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c29tZXdvcmRwcmVzcw==
  MYSQL_PASSWORD: d29yZHByZXNz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: db-namespace
  labels:
    id: C0908671
    app: db-deployment
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: C0908671
      app: db-deployment
  template:
    metadata:
      labels:
        id: C0908671
        app: db-deployment
    spec:
      containers:
      - name: mysql-app
        image: mariadb:10.6.4-focal
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        envFrom:
        - configMapRef:
            name: db-configmap
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 3306
      volumes:
      - name: mysql-persistent-storage

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db-namespace
spec:
  type: ClusterIP
  selector:
    id: C0908671
    app: db-deployment
  ports:
    - port: 3306
      targetPort: 3306
