#default
#common stuff is put here

db:
  name: wp-database
  labels:
    id: C0908671
    app: db
    env: dev
    stack: wordpress
  image:
    repository: mariadb:10.6.4-focal
    tag: v1
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    APP_ENV: dev
  containerPorts:
    mysql: 3306
