---
# Source: wordpress-db/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-database-configmap
  labels:
    app: db
    env: dev
    id: C0908671
data:
  APP_ENV: "dev"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wordpress"
